feat: Add keepScreenshot option (usefull for reports)
Visual-Regression-Tracker/agent-cypress pull request #159
Opened 2021-09-16 13:29 UTC by Eduard-iCH

Cypress agent currently auto-delete all taked (with vrtTake()) screenshots . This PR make this behavior optional.
Usefull to fix error with reporters, like Mochawesome for Cypress:
![image](https://user-images.githubusercontent.com/33355363/133620654-e61f0e3b-a07e-4ea0-bc92-fdd339acfaa8.png)

2021-09-16 19:47 UTC, pashidlos requested changes

2021-09-16 19:47 UTC, pashidlos commented on lib/plugin.js
> +      if (props.keepScreenshot !== true) { unlinkSync(props.imagePath); }
```suggestion
      if (!props.keepScreenshot) { 
           unlinkSync(props.imagePath); 
      }
```

2021-09-16 19:47 UTC, pashidlos commented on README.md
> +  keepScreenshot: false, // Keep screenshot copy on the user's disk
```suggestion
  keepScreenshot: false, // Keep screenshot local copy
```

2021-09-16 19:47 UTC, pashidlos commented on lib/index.ts
> +    keepScreenshot?: boolean;
could we add this only to `vrtTrack` command as the others would not utilise this option ?

2022-07-05 02:37 UTC, dimitriharding commented
@pashidlos Can I pick this up? Switching to Cypress 10, and need to use `Mochawesome` as an HTML reporter. That `unlinkSync` is causing an issue, would love to have it optional.

2022-07-12 14:15 UTC, closed without merging